In [2]:
import torch

In [3]:
x = torch.tensor(1.0, requires_grad=True)
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

y = x * w + b

In [4]:
y.backward()


In [5]:
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [6]:
X = torch.normal(0, 1, (2, 2), requires_grad=True)
w = torch.normal(0, 1, (2, 1), requires_grad=True)
b = torch.zeros((2, 1),requires_grad=True)

y = torch.matmul(X, w) + b

In [7]:
out = y.norm()
out.backward()

print(y)
print(out)
print(X)
print(w)
print(b)
print('---')
print(X.grad)
print(w.grad)
print(b.grad)

tensor([[-0.1228],
        [-0.9045]], grad_fn=<AddBackward0>)
tensor(0.9128, grad_fn=<LinalgVectorNormBackward0>)
tensor([[-0.2720,  0.8215],
        [ 0.8448,  0.6964]], requires_grad=True)
tensor([[-0.7443],
        [-0.3959]], requires_grad=True)
tensor([[0.],
        [0.]], requires_grad=True)
---
tensor([[0.1001, 0.0533],
        [0.7376, 0.3923]])
tensor([[-0.8005],
        [-0.8005]])
tensor([[-0.1345],
        [-0.9909]])


In [8]:
w.grad.zero_()

tensor([[0.],
        [0.]])

In [9]:
y = torch.matmul(X, w) + b
y

tensor([[-0.1228],
        [-0.9045]], grad_fn=<AddBackward0>)